### ISSUE TITLE
--version and -v flags don't actually print the version number

### ISSUE THREAD

**Issue by rraub** [cloudflare/logshare#1]
I just cloned this tool and upon testing it out, I noticed the version flags don't work. They just print the string `logshare-cli version` instead of a version number.

```
$ logshare-cli -v
logshare-cli version 
$ logshare-cli --version
logshare-cli version 
```

**Comment by elithrar** [comment]
Thanks - was missing an ldflags arg in my Travis config. Now fixed in https://github.com/cloudflare/logshare/releases/tag/v1.1
