### ISSUE TITLE
`ray-id` parameter not accepted

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/logshare#14]
Hello! 👋 

Coming from another provider, I've been loving this tooling so thanks a bunch for that!

Reading through the docs, I had a need today to fetch a specific Ray ID and I expected the following to work and just return me a single log entry.

```
logshare-cli --api-key=$CF_API_KEY \ 
             --api-email=$CF_API_EMAIL \
             --zone-name=$CF_ZONE_NAME \ 
             --count 1 \ 
             --ray-id $CF_RAY_ID
```

However I get a HTTP 400 response back from the service. I dug into it a bit and the request is being made to `https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/logs/received?start_id=$CF_RAY_ID&end=1513316400&count=1` and the response is `bad query parameter: query arguments are limited to: start,end,fields,count,sample,timestamps` which by the looks of things seems like it isn't a valid field anymore.

I did manage to see that I can use a Ray ID parameter providing that `--legacy-endpoint` is passed and it ends up hitting `https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/logs/requests?start_id=$CF_RAY_ID&end=1513316891&count=1` instead. 

My questions on this bit of functionality (and how you intend it to work):

- Is `--ray-id`/`start_id` compatibility coming to the `logs/received` endpoint? or;
- Should `--legacy-endpoint` be a given if the `--ray-id` value is set?

Happy to PR some docs or the change for this one if you can advise on the above 🍭

**Comment by elithrar** [comment]
Hi there,

• Per- RayID filtering won’t be coming to the new endpoint
• We will be deprecating the legacy endpoint in early 2018, and thus prefer
users to make a decision to use the legacy endpoint.

To be transparent: the legacy endpoint has had performance issues (part of
that being RayID-based indexes) for large zones, issues with late-arriving
data ordering, as well as an overly-verbose log format, which drove us to
solve that with the “received” endpoint.

We are looking at what filtering options we can add to the new endpoint,
but those will be much broader - e.g. all errors, all security events.
