### ISSUE TITLE
cannot get logs

### ISSUE THREAD

**Issue by wasiflaeeq** [cloudflare/logshare#15]
./logshare --api-key=removed --api-email=removed --zone-name=removed.com 

I am not sure, what I am doing wrong... 

It returns [logshare-cli] 15:59:07 Retrieved 0 logs

./logshare -v
logshare-cli version 8c69caf

**Comment by wasiflaeeq** [comment]
--list-fields seems to be working fine. Do I need to get ELS service activated from cloudflare to pull the logs? This domain is already on enterprise plan...

**Comment by elithrar** [comment]
Hi @wasiflaeeq - can you confirm:

* you have an Enteprise domain on Cloudflare (logs are an Enterprise only feature)
* you had active requests during that timeframe? Note that the default timeframe is -30 to -20 minutes from the present.

If you are still having issues, email me at msilverlock @ Cloudflare with the zone & user you’re attempting to fetch logs for.

**Comment by wasiflaeeq** [comment]
Yes, Domain is on enterprise plan. and there are active requests in analytics... 
using legacy endpoint it returns

[logshare-cli] 16:15:27 failed to fetch via timestamp: HTTP status 204: no logs available. Check that Log Share is enabled for your domain or that you are not attempting to retrieve logs too quickly

**Comment by elithrar** [comment]
Please raise a ticket with Support and they’ll be able to turn on logs for
all future requests for each zone.
