### ISSUE TITLE
fields not working?

### ISSUE THREAD

**Issue by jbilbro** [cloudflare/logshare#19]
Hello-

In the previous version the following was working for me:

`logshare-cli --api-key=supersecret --api-email=myemail@example.com --zone-name=example.com --end-time="$(date +\%s --date '-29 min')" --count=-1 --fields="ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestURI,ClientRequestUserAgent,CacheCacheStatus,ClientDeviceType,ClientRequestProtocol,ClientRequestReferer,ClientSSLProtocol,ClientRequestReferer,ClientSSLProtocol,OriginResponseBytes,OriginResponseHTTPExpires,OriginResponseStatus,EdgeResponseStatus,EdgeEndTimestamp,OriginResponseTime,WAFAction,WAFRuleID,RayID"`

Now, however, I'm getting the default fields and I haven't been able to figure out how to get it to honor the list of fields.  Am I doing something wrong?

**Comment by elithrar** [comment]
Hi @jbilbro - see the release notes here: https://github.com/cloudflare/logshare/releases/tag/v1.4.1

**Comment by jbilbro** [comment]
That is for single fields, though, yes?  I'm passing a long list of fields and it's being ignored.  Am I doing something wrong?  I did delete it and re-go get the logshare-cli binary prior to putting in this issue, though I can't tell what version I'm running:

`[devops@cf-logger bin]$ ./logshare-cli --version
logshare-cli version`

**Comment by elithrar** [comment]
You may have caught the version with the bug. What is the HEAD of your
repo? `git rev-parse HEAD`

If it's one of:

e454b8e [build] Remove binary from repo. (#17)
a955be5 (tag: v1.4.0) [feat] Support timestamp formats & sampling (#16)

... then you may see issues.

Working example on v1.4.1 (ace2e393f26432afd742695f79baf6830ea32380):

logshare-cli --api-email=$(echo $CF_API_EMAIL) --api-key=$(echo
$CF_API_KEY) --zone-name=questionable.services --count=1
--start-time=`hours-ago 4`
--fields=ClientIP,ClientRequestURI,ClientRequestMethod,EdgeStartTimestamp |
jq
[logshare-cli] 15:29:59 HTTP status 200 | 4504ms |
https://api.cloudflare.com/client/v4/zones/{zoneID}/logs/received?count=1&end=1515712193&fields=ClientIP%2CClientRequestURI%2CClientRequestMethod%2CEdgeStartTimestamp&start=1515698993&timestamps=unixnano
[logshare-cli] 15:29:59 Retrieved 1 logs

{
  "ClientIP": "2606:4700:2001:10b::16",
  "ClientRequestMethod": "GET",
  "ClientRequestURI": "/",
  "EdgeStartTimestamp": 1515707693927000000
}

**Comment by jbilbro** [comment]
Ah, right you are.  Sorry for the confusion - looks like I hadn't entirely blown away the old version when I pulled it down again.  Happy now!
