### ISSUE TITLE
Support for new endpoint

### ISSUE THREAD

**Issue by mralexho** [cloudflare/logshare#22]
Hello,

Our team is using this tool to ingest logs into our log management service. Will there be support for the new `/received` endpoint mentioned on https://support.cloudflare.com/hc/en-us/articles/115003165991-Enterprise-Log-Share-ELS-Migrating-to-New-Endpoint?

Thanks.

**Comment by mralexho** [comment]
Sorry, there was some internal miscommunication with this tool. Closing ticket.

**Comment by elithrar** [comment]
The new /received endpoint is supported by default 🌟
