### ISSUE TITLE
client dest through options

### ISSUE THREAD

**Issue by saurabhguptag** [cloudflare/logshare#6]
Can we have the following changes to have configurable destination of output?

On line 84 of logshare.go from 
`if options != nil && options.Fields != nil {
	client.fields = options.Fields
}`

to 

`if options != nil {
	if options.Fields != nil {
		client.fields = options.Fields
	}
	if options.Dest != nil {
		client.dest = options.Dest
	}
}`

or anything better.

**Comment by elithrar** [comment]
- How do you want to specify destinations?
- Do you want to output to a file?

If the latter, right now you can redirect output to a file, so I’m curious
to understand your use case more.

**Comment by saurabhguptag** [comment]
Cloudflare currently only gives out combined domain analytics on its panel but not segregated based on subdomain, So to get that information I am only left out to loop through the logshare data. Now thanks to new received APIs we can filter the log fields and making manageable to store data at our end.

so I am planning to write wrapper around logshare project for our account which would post the data to either ELK or influx or either store the data to Filesystem and parse and push. 

Do you have a solutions for my issue which could help me skip all this steps?

**Comment by elithrar** [comment]
There are no current solutions from us, although many customers have their
own tooling to do this. We're investigating extending this CLI to push to
the ElasticSearch bulk API, but no timeline (to be transparent: no
resources committed to that yet)
